# Generated by Django 5.2 on 2026-08-31 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0022_alter_testcasestep_expected_result'),
        ('ui_automation', '0022_uiauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='execution_mode',
            field=models.CharField(blank=True, choices=[('hybrid', '智能双模(脚本优先+AI介入)'), ('script_only', '仅脚本执行'), ('ai_only', '纯AI执行')], default='hybrid', max_length=20, verbose_name='默认执行模式'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='ui_test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bound_testcases', to='ui_automation.uitestcase', verbose_name='绑定的UI自动化用例'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='ai_diagnosis',
            field=models.JSONField(blank=True, null=True, verbose_name='AI诊断报告'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='execution_mode',
            field=models.CharField(blank=True, default='hybrid', max_length=20, verbose_name='执行模式'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='is_ai_intervened',
            field=models.BooleanField(default=False, verbose_name='是否AI介入'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='self_healing_info',
            field=models.JSONField(blank=True, null=True, verbose_name='自愈信息'),
        ),
        migrations.AddField(
            model_name='testcaseresult',
            name='ui_execution_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcase_results', to='ui_automation.uiexecutionrecord', verbose_name='关联的UI执行记录'),
        ),
    ]
