# Generated by Django 5.2 on 2026-09-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0013_capabilitydefinition_generationoutput_capability_and_more'),
        ('testcases', '0027_review_documents_and_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='knowledge_evolution.capabilitydefinition', verbose_name='能力定义'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='source_output',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='knowledge_evolution.generationoutput', verbose_name='来源产出'),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='workflow_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='工作流ID'),
        ),
    ]
