# Generated by Django 5.2 on 2026-09-07 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='WHartTest', help_text='显示在浏览器标签页上的文字', max_length=255, verbose_name='平台浏览器标题')),
                ('name', models.CharField(default='WHartTest', help_text='侧边栏和主界面显示的平台Logo旁文本', max_length=255, verbose_name='平台名称')),
                ('login_title', models.CharField(default='WHartTest', help_text='登录页面主标题', max_length=255, verbose_name='登录页标题')),
                ('login_subtitle', models.CharField(default='小麦智测自动化平台', help_text='登录页面标题下方的描述文字', max_length=500, verbose_name='登录页副标题')),
                ('login_tags', models.TextField(default='AI 智能生成, RAG 知识库, MCP 工具调用, Skills 技能库, Playwright 自动化, LangGraph, 接口自动化', help_text='登录页面显示的平台特色标签，用逗号或中文逗号分隔', verbose_name='登录页特色标签')),
                ('logo_url', models.TextField(blank=True, default='', help_text='若为空则展示系统默认Logo，支持完整HTTP图片地址或data:image/png;base64,...', verbose_name='自定义Logo图片Base64或URL')),
                ('brand_badge_enabled', models.BooleanField(default=True, help_text='控制登录页标题右侧及系统导航栏品牌文字右侧的角标是否显示', verbose_name='品牌角标是否显示')),
                ('brand_badge_url', models.TextField(blank=True, default='/PE.svg', help_text='用于登录页标题右侧及系统导航栏品牌文字右侧的角标，支持完整HTTP图片地址、站内路径或data:image/svg+xml;base64,...', verbose_name='品牌角标图片Base64或URL')),
                ('operation_log_retention_days', models.PositiveIntegerField(default=7, help_text='自动清理超过保留天数的操作日志，默认 7 天', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3650)], verbose_name='操作日志自动清理天数')),
            ],
            options={
                'verbose_name': '系统全局配置',
                'verbose_name_plural': '系统全局配置',
            },
        ),
        migrations.CreateModel(
            name='UserLoginState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_version', models.PositiveBigIntegerField(default=0, help_text='每次登录 +1；旧版本 access/refresh token 均失效', verbose_name='会话版本号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_state', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户登录状态',
                'verbose_name_plural': '用户登录状态',
            },
        ),
    ]
