from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = [("projects", "0004_remove_project_password_remove_project_system_url_and_more"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="GitLabConnection", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("base_url", models.URLField(max_length=500)), ("verify_ssl", models.BooleanField(default=True)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ["name"]}),
        migrations.CreateModel(name="ProjectRepository", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("gitlab_project_id", models.CharField(max_length=255)), ("name", models.CharField(max_length=255)), ("path_with_namespace", models.CharField(max_length=500)), ("default_branch", models.CharField(default="main", max_length=255)), ("languages", models.JSONField(blank=True, default=list)), ("excluded_patterns", models.JSONField(blank=True, default=list)), ("critical_annotations", models.JSONField(blank=True, default=list)), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="repositories", to="code_analysis.gitlabconnection")), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_repositories", to="projects.project"))], options={"ordering": ["name"], "unique_together": {("project", "connection", "gitlab_project_id")}}),
        migrations.CreateModel(name="UserGitLabCredential", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("encrypted_token", models.TextField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("connection", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="code_analysis.gitlabconnection")), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="gitlab_credentials", to="projects.project")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))], options={"unique_together": {("project", "connection", "user")}}),
        migrations.CreateModel(name="AnalysisTask", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("source_type", models.CharField(choices=[("merge_request", "Merge Request"), ("commits", "Commit比较")], max_length=20)), ("merge_request_iid", models.PositiveIntegerField(blank=True, null=True)), ("base_sha", models.CharField(blank=True, max_length=64)), ("head_sha", models.CharField(blank=True, max_length=64)), ("title", models.CharField(blank=True, max_length=500)), ("mode", models.CharField(choices=[("quick", "快速"), ("standard", "标准"), ("deep", "深度")], default="standard", max_length=20)), ("status", models.CharField(choices=[("pending", "待执行"), ("fetching", "获取代码中"), ("machine_analyzing", "机器分析中"), ("ai_analyzing", "AI分析中"), ("generating_tests", "生成测试报告中"), ("completed", "已完成"), ("partial", "部分完成"), ("failed", "失败"), ("cancelled", "已取消")], db_index=True, default="pending", max_length=30)), ("progress", models.PositiveSmallIntegerField(default=0)), ("current_step", models.CharField(blank=True, max_length=255)), ("error_message", models.TextField(blank=True)), ("change_report", models.JSONField(blank=True, default=dict)), ("test_report", models.JSONField(blank=True, default=dict)), ("raw_diff", models.TextField(blank=True)), ("machine_coverage", models.FloatField(default=0)), ("ai_coverage", models.FloatField(default=0)), ("token_usage", models.PositiveIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("completed_at", models.DateTimeField(blank=True, null=True)), ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_analysis_tasks", to=settings.AUTH_USER_MODEL)), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="code_analysis_tasks", to="projects.project")), ("repository", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="analysis_tasks", to="code_analysis.projectrepository"))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="TestRequirementDraft", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=500)), ("objective", models.TextField(blank=True)), ("expected_result", models.TextField(blank=True)), ("priority", models.CharField(default="medium", max_length=20)), ("test_type", models.CharField(default="功能回归", max_length=100)), ("source_finding_key", models.CharField(blank=True, max_length=255)), ("status", models.CharField(choices=[("draft", "AI草稿"), ("accepted", "已采纳"), ("ignored", "已忽略"), ("converted", "已转用例")], default="draft", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="test_requirement_drafts", to="code_analysis.analysistask"))]),
    ]
