# Generated by Codex
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('langgraph_integration', '0026_restore_llmconfig_table_if_missing'),
    ]

    operations = []
