# Generated by hand on 2026-05-24 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_integration', '0027_chatsession_resolved_runtime_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': '对话消息', 'verbose_name_plural': '对话消息'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='消息内容'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='单张图片(兼容)'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='图片列表'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_id',
            field=models.CharField(db_index=True, help_text='LangGraph消息的唯一标识符', max_length=255, verbose_name='消息ID'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('system', '系统'), ('human', '用户'), ('ai', '助手'), ('tool', '工具'), ('unknown', '未知')], max_length=20, verbose_name='角色/类型'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
