# Generated by Django 5.2 on 2026-09-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_add_anonymize_document_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='block_type',
            field=models.CharField(blank=True, choices=[('heading', '标题'), ('paragraph', '段落'), ('table', '表格'), ('code_block', '代码块'), ('list', '列表'), ('mixed', '合并块')], help_text='分块来源的结构类型', max_length=32, null=True, verbose_name='块类型'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='location',
            field=models.JSONField(blank=True, default=dict, help_text='原文定位：page/section/heading_level/table_index/code_lang 等', verbose_name='来源定位'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='section_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='章节标题'),
        ),
    ]
