export interface GitLabConnection { id: number; name: string; base_url: string; verify_ssl: boolean; is_active: boolean; repository_count?: number }
export interface CodeRepository { id: number; project: number; source_type: 'gitlab'|'local_git'; connection?: number; connection_name?: string; name: string; path_with_namespace: string; gitlab_project_id?: string; local_path?: string; default_branch: string; analysis_task_count?: number }
export interface MergeRequest { iid: number; title: string; source_branch: string; target_branch: string; author?: { name: string } }
export interface RepositoryCommit { id: string; short_id: string; title: string; author_name?: string; authored_date?: string }
export interface AnalysisExecutionLog { id: number; event: string; message: string; detail?: Record<string, any>; actor_name: string; created_at: string }
export interface TestRequirementDraft { id: number; title: string; status: 'draft'|'accepted'|'ignored'|'converted'; converted_test_case?: number|null }
export interface Finding { key: string; change: string; file: string; severity: string; source: string; confidence: number; evidence: string; impact: string; trigger?: string; recommendation?: string; disposition?: 'confirmed'|'needs_confirmation'|'advisory'; verdict?: 'confirmed'|'needs_confirmation'|'rejected'|'advisory'; verification_status?: 'supported'|'partially_supported'|'refuted'|'inconclusive'|'verification_failed'; verification_reason?: string; supporting_evidence?: string[]; counter_evidence?: string|string[]; trigger_reachable?: boolean; target_commit_verified?: boolean; line_start?: number; line_side?: 'old'|'new'; diff_header?: string; change_lines?: Array<{type:'added'|'removed'|'context';old_line?:number|null;new_line?:number|null;content:string}>; related_diff?: string; related_diff_error?: string; verified?: boolean; suggested_patch?: string; patch_status?: 'applicable'|'reference'; patch_validation_message?: string }
export interface GraphEntity { id?: number|string; kind?: string; name?: string; qualified_name?: string; file?: string; file_path?: string; source?: string; target?: string; line?: number; line_start?: number; coverage?: string; criticality?: string; steps?: GraphEntity[] }
export interface GraphContext { status?: 'completed'|'unavailable'|'skipped'; graph_commit?: string; counts?: Record<string, number>; preview?: { changed_symbols?: GraphEntity[]; affected_files?: string[]; callers?: GraphEntity[]; related_tests?: GraphEntity[]; affected_flows?: GraphEntity[]; test_gaps?: GraphEntity[] }; coverage?: {requested_changed_files?:number;mapped_changed_files?:number;unmapped_changed_files?:string[];parse_status?:string}; truncation?: {truncated?:boolean}; duration_ms?: number; diagnostics?: {prepare_ms?:number;query_ms?:number;crg_version?:string;parse_status?:string;node_count?:number;edge_count?:number;degraded_reason?:string}; crg_version?: string }
export interface ReviewFile { path:string; additions?:number; deletions?:number; excluded?:boolean; exclusion_reason?:string }
export interface TestRequirement { id?:number; title:string; objective:string; expected_result:string; priority?:string; test_type?:string; source_finding_key?:string; change_group?:string; risk_reference?:{title?:string;file?:string} }
export interface OcrDiagnostics { optimization?:{strategy?:string;duplicate_ai_files_avoided?:number;total_analyzable_files?:number}; fallback?:{triggered?:boolean;file_count?:number;coverage?:number;effective_coverage?:number;status?:string}; [key:string]:unknown }
export interface AnalysisTask { id: string; project: number; repository: number; repository_name: string; creator_name: string; source_type: 'merge_request'|'commits'; merge_request_iid?: number; base_sha: string; head_sha: string; title: string; requirement_context?: string; api_context?: string; requirement_document_ids?: string[]; api_document_ids?: string[]; knowledge_base_ids?: string[]; knowledge_document_ids?: string[]; mode: string; status: string; progress: number; current_step: string; error_message: string; machine_coverage: number; ai_coverage: number; token_usage: number; test_requirement_drafts?: TestRequirementDraft[]; change_report: { summary?: Record<string, number>; files?: ReviewFile[]; findings?: Finding[]; impact_modules?: Array<{module:string;change_type:string;impact:string;regression_scope:string}>; impact_summary?: string[]; analysis_note?: string; graph_context?: GraphContext; coverage?: {scope_files?:number;analyzed_files?:number;excluded_files?:number;machine_percent?:number;ai_percent?:number}; ocr_status?: {status:'completed'|'partial'|'failed'|'skipped';message:string;coverage:number;diagnostics?:OcrDiagnostics} }; test_report: { summary?: Record<string, number>; iteration_summary?: { title?: string; description?: string; summary_points?: string[]; change_items?: string[]; change_groups?: Array<{ module?:string; name:string; description:string; change_scale?:'large'|'medium'|'small'; files?:string[]; test_focus:string }> }; test_requirements?: TestRequirement[]; regression_suggestions?: string[]; coverage_gaps?: string[] }; created_at: string; completed_at?: string }
export interface AnalysisTask { project_name?: string }
