# Generated by Django 5.2 on 2026-09-29 14:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("knowledge", "0019_add_anonymize_document_permission"),
        ("projects", "0004_remove_project_password_remove_project_system_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalTrace",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_type", models.CharField(db_index=True, max_length=64)),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("query", models.TextField()),
                ("rewritten_query", models.TextField(blank=True)),
                ("policy_version", models.CharField(default="knowledge-legacy-v1", max_length=128)),
                ("status", models.CharField(choices=[("completed", "已完成"), ("failed", "失败"), ("untraceable", "不可进入飞轮")], default="completed", max_length=20)),
                ("channels", models.JSONField(blank=True, default=dict)),
                ("candidates", models.JSONField(blank=True, default=list)),
                ("citations", models.JSONField(blank=True, default=list)),
                ("timings", models.JSONField(blank=True, default=dict)),
                ("token_usage", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("knowledge_base", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retrieval_traces", to="knowledge.knowledgebase")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="retrieval_traces", to="projects.project")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="retrieval_traces", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"], "permissions": [("export_retrievaltrace", "Can export retrieval traces")]},
        ),
        migrations.CreateModel(
            name="GenerationOutput",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_type", models.CharField(db_index=True, max_length=64)),
                ("task_id", models.CharField(blank=True, db_index=True, max_length=128)),
                ("model_version", models.CharField(blank=True, max_length=200)),
                ("prompt_version", models.CharField(default="knowledge-template-v1", max_length=128)),
                ("content", models.TextField()),
                ("output_hash", models.CharField(db_index=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="generation_outputs", to="projects.project")),
                ("trace", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="generation_output", to="knowledge_evolution.retrievaltrace")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="FeedbackEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("knowledge_version_ids", models.JSONField(blank=True, default=list)),
                ("signal", models.CharField(choices=[("accepted", "采纳"), ("rejected", "驳回"), ("edited", "编辑"), ("test_passed", "测试通过"), ("test_failed", "测试失败"), ("defect_confirmed", "缺陷确认"), ("false_positive", "误报"), ("missed", "漏报"), ("merged", "已合并"), ("reverted", "已回退")], db_index=True, max_length=32)),
                ("value", models.FloatField(default=1.0)),
                ("reason_code", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField(blank=True)),
                ("actor_type", models.CharField(choices=[("user", "用户"), ("system", "系统"), ("integration", "集成")], default="user", max_length=20)),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("occurred_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="knowledge_feedback_events", to=settings.AUTH_USER_MODEL)),
                ("output", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="feedback_events", to="knowledge_evolution.generationoutput")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="knowledge_feedback_events", to="projects.project")),
                ("trace", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="feedback_events", to="knowledge_evolution.retrievaltrace")),
            ],
            options={"ordering": ["-occurred_at", "-created_at"]},
        ),
        migrations.AddIndex(model_name="retrievaltrace", index=models.Index(fields=["project", "task_type", "created_at"], name="knowledge_e_project_958e12_idx")),
        migrations.AddIndex(model_name="retrievaltrace", index=models.Index(fields=["knowledge_base", "created_at"], name="knowledge_e_knowled_1c0f9e_idx")),
        migrations.AddIndex(model_name="generationoutput", index=models.Index(fields=["project", "task_type", "created_at"], name="knowledge_e_project_efb203_idx")),
        migrations.AddIndex(model_name="feedbackevent", index=models.Index(fields=["project", "signal", "occurred_at"], name="knowledge_e_project_6706d2_idx")),
        migrations.AddIndex(model_name="feedbackevent", index=models.Index(fields=["trace", "signal"], name="knowledge_e_trace_i_28fc7a_idx")),
    ]
