# Generated by Django 5.2 on 2026-09-29 15:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0019_add_anonymize_document_permission'),
        ('knowledge_evolution', '0001_initial'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeAsset',
            fields=[
                ('acl_tags', models.JSONField(blank=True, default=list)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('concept', '概念'), ('rule', '规则/约束'), ('fact', '事实'), ('procedure', '流程/步骤'), ('failure_case', '故障案例'), ('standard', '规范条文')], db_index=True, max_length=32)),
                ('key', models.CharField(db_index=True, help_text='归一化后的稳定业务标识', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('L1', 'L1 强制'), ('L2', 'L2 应当参考'), ('L3', 'L3 可选参考')], db_index=True, default='L3', max_length=2)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '生效中'), ('review_due', '待复核'), ('deprecated', '已废弃'), ('archived', '已归档')], db_index=True, default='draft', max_length=20)),
                ('applicability', models.JSONField(blank=True, default=dict, help_text='适用域：产品线/版本/环境/语言等限定条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_assets', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_knowledge_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_assets', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_knowledge_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type', 'key'],
                'permissions': [('publish_knowledgeasset', 'Can publish a knowledge asset version'), ('resolve_knowledgeconflict', 'Can resolve a knowledge conflict')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('content', models.TextField(help_text='知识原子：对象 + 约束/行为 + 条件 + 适用域')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending_eval', '待评测'), ('awaiting_approval', '待审批'), ('published', '已发布'), ('review_due', '待复核'), ('deprecated', '已废弃'), ('rolled_back', '已回滚'), ('rejected', '已驳回')], db_index=True, default='pending_eval', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_versions', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge_evolution.knowledgeasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_versions', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='knowledge_evolution.knowledgeversion')),
                ('second_approver', models.ForeignKey(blank=True, help_text='L1 强制知识的第二审批人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_approved_knowledge_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset', '-version'],
                'permissions': [('approve_l1_knowledgeversion', 'Can approve an L1 knowledge version')],
            },
        ),
        migrations.AddField(
            model_name='knowledgeasset',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_of_assets', to='knowledge_evolution.knowledgeversion'),
        ),
        migrations.CreateModel(
            name='IndexProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index_type', models.CharField(choices=[('qdrant_dense', 'Qdrant 稠密向量'), ('qdrant_sparse', 'Qdrant 稀疏向量'), ('document_graph', '文档图谱'), ('keyword', '关键词索引')], db_index=True, max_length=32)),
                ('projection_version', models.CharField(db_index=True, help_text='投影代数：分块器/embedding 模型版本，alias 切换的比较基准', max_length=100)),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('vector_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('pending', '待写入'), ('writing', '写入中'), ('ready', '已就绪'), ('failed', '写入失败'), ('stale', '已过期'), ('removed', '已回收')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_projections', to='projects.project')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='knowledge_evolution.knowledgeversion')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('acl_tags', models.JSONField(blank=True, default=list)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('document', '文档'), ('code_commit', '代码快照'), ('requirement', '需求'), ('test_case', '测试用例'), ('test_run', '测试执行'), ('defect', '缺陷'), ('review_result', '审查结果'), ('manual_review', '人工评审'), ('conversation', '对话'), ('experience', '经验蒸馏')], db_index=True, max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=255)),
                ('revision', models.CharField(blank=True, max_length=255)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('authority', models.CharField(choices=[('official', '官方/权威来源'), ('standard', '标准/规范'), ('approved', '已审批内部来源'), ('internal', '内部一般来源'), ('external', '外部参考'), ('derived', '派生生成')], db_index=True, default='internal', max_length=20)),
                ('status', models.CharField(choices=[('captured', '已采集'), ('parsed', '已解析'), ('extracted', '已提取'), ('failed', '处理失败'), ('superseded', '已被新快照取代')], db_index=True, default='captured', max_length=20)),
                ('location', models.JSONField(blank=True, default=dict, help_text='来源定位：页码/章节/表格位置，或 repo+commit+file+line')),
                ('raw_content', models.TextField(blank=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('parser_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_snapshots', to=settings.AUTH_USER_MODEL)),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_snapshots', to='knowledge.knowledgebase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('export_sourcesnapshot', 'Can export knowledge source snapshots')],
            },
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='source_snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='knowledge_evolution.sourcesnapshot'),
        ),
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('supported_by', '由…支持'), ('derived_from', '派生自'), ('refuted_by', '被…反驳'), ('contradicts', '与…矛盾')], db_index=True, default='supported_by', max_length=20)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('location_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('excerpt', models.TextField(blank=True)),
                ('weight', models.FloatField(default=1.0)),
                ('extractor_version', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='knowledge_evolution.knowledgeversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidences', to='knowledge_evolution.sourcesnapshot')),
            ],
            options={
                'ordering': ['-weight', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('concept', '概念'), ('rule', '规则/约束'), ('relation', '关系'), ('summary', '摘要'), ('knowledge_atom', '知识原子'), ('experience', '二次经验')], db_index=True, max_length=32)),
                ('origin', models.CharField(choices=[('extraction', '结构提取'), ('distillation', '反馈蒸馏'), ('manual', '人工录入'), ('evaluation_failure', '评测失败样本')], default='extraction', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('level', models.CharField(choices=[('L1', 'L1 强制'), ('L2', 'L2 应当参考'), ('L3', 'L3 可选参考')], default='L3', help_text='候选建议的分级，需审批确认', max_length=2)),
                ('confidence', models.FloatField(default=0.5)),
                ('evidence', models.JSONField(blank=True, default=list, help_text='候选阶段的证据引用：snapshot_id + location + relation + weight')),
                ('feedback_event_ids', models.JSONField(blank=True, default=list, help_text='二次蒸馏候选的来源反馈事件（R6 四级关联）')),
                ('state', models.CharField(choices=[('pending', '待处理'), ('conflicted', '存在冲突'), ('evaluating', '评测中'), ('awaiting_approval', '待审批'), ('accepted', '已采纳'), ('rejected', '已驳回'), ('merged', '已合并到既有资产')], db_index=True, default='pending', max_length=20)),
                ('dedup_key', models.CharField(help_text='去重键：project + kind + 归一化内容哈希', max_length=64, unique=True)),
                ('extracted_by', models.CharField(blank=True, help_text='提取器版本', max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=128)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_candidates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_candidates', to='projects.project')),
                ('promoted_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_candidates', to='knowledge_evolution.knowledgeasset')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_candidates', to=settings.AUTH_USER_MODEL)),
                ('source_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='knowledge_evolution.sourcesnapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('review_knowledgecandidate', 'Can review a knowledge candidate')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('user', '用户'), ('system', '系统'), ('integration', '集成')], default='user', max_length=20)),
                ('action', models.CharField(choices=[('create', '创建'), ('transition', '状态流转'), ('publish', '发布'), ('rollback', '回滚'), ('conflict_resolved', '冲突裁决'), ('acl_change', '权限变更')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('from_state', models.CharField(blank=True, max_length=32)),
                ('to_state', models.CharField(blank=True, max_length=32)),
                ('before_version', models.PositiveIntegerField(blank=True, null=True)),
                ('after_version', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_audit_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'created_at'], name='knowledge_e_project_c13add_idx'), models.Index(fields=['entity_type', 'entity_id', 'created_at'], name='knowledge_e_entity__0a7a8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conflict_type', models.CharField(choices=[('contradiction', '结论矛盾'), ('temporal', '时效冲突'), ('scope_overlap', '适用域重叠'), ('duplicate', '近重复')], db_index=True, max_length=32)),
                ('state', models.CharField(choices=[('open', '待处理'), ('resolving', '处理中'), ('resolved', '已解决'), ('dismissed', '已忽略')], db_index=True, default='open', max_length=20)),
                ('resolution', models.CharField(choices=[('pending', '未裁决'), ('prefer_left', '采信左'), ('prefer_right', '采信右'), ('merge', '合并'), ('coexist', '限定适用域后共存'), ('both_deprecated', '双方废弃')], db_index=True, default='pending', max_length=20)),
                ('trust_penalty', models.FloatField(default=0.5, help_text='未解决期间检索信任折减系数（R3）')),
                ('detail', models.TextField(blank=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('detected_by', models.CharField(blank=True, max_length=100)),
                ('detector_version', models.CharField(blank=True, max_length=100)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_left', to='knowledge_evolution.knowledgeasset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_conflicts', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_knowledge_conflicts', to=settings.AUTH_USER_MODEL)),
                ('right_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_right', to='knowledge_evolution.knowledgeasset')),
                ('left_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_left', to='knowledge_evolution.knowledgeversion')),
                ('right_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_as_right', to='knowledge_evolution.knowledgeversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'state', 'created_at'], name='knowledge_e_project_4e25f8_idx'), models.Index(fields=['project', 'conflict_type'], name='knowledge_e_project_7f1b8c_idx')],
                'constraints': [models.UniqueConstraint(fields=('left_asset', 'right_asset', 'conflict_type'), name='uniq_conflict_pair_type')],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgeasset',
            index=models.Index(fields=['project', 'level', 'status'], name='knowledge_e_project_25a2b1_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeasset',
            index=models.Index(fields=['project', 'status', 'updated_at'], name='knowledge_e_project_acb4d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeasset',
            constraint=models.UniqueConstraint(fields=('project', 'asset_type', 'key'), name='uniq_asset_project_type_key'),
        ),
        migrations.AddIndex(
            model_name='indexprojection',
            index=models.Index(fields=['project', 'index_type', 'state'], name='knowledge_e_project_35cbf3_idx'),
        ),
        migrations.AddIndex(
            model_name='indexprojection',
            index=models.Index(fields=['projection_version', 'state'], name='knowledge_e_project_51bdd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='indexprojection',
            constraint=models.UniqueConstraint(fields=('version', 'index_type', 'projection_version'), name='uniq_projection_version_type_gen'),
        ),
        migrations.AddIndex(
            model_name='sourcesnapshot',
            index=models.Index(fields=['project', 'source_type', 'created_at'], name='knowledge_e_project_c1c676_idx'),
        ),
        migrations.AddIndex(
            model_name='sourcesnapshot',
            index=models.Index(fields=['project', 'authority'], name='knowledge_e_project_7ff327_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcesnapshot',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'revision', 'content_hash'), name='uniq_snapshot_source_revision_hash'),
        ),
        migrations.AddIndex(
            model_name='knowledgeversion',
            index=models.Index(fields=['asset', 'status'], name='knowledge_e_asset_i_f2febd_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeversion',
            index=models.Index(fields=['status', 'expires_at'], name='knowledge_e_status_7b8326_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeversion',
            constraint=models.UniqueConstraint(fields=('asset', 'version'), name='uniq_version_asset_version'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['version', 'relation'], name='knowledge_e_version_24ff10_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeevidence',
            index=models.Index(fields=['snapshot', 'relation'], name='knowledge_e_snapsho_eac7ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgeevidence',
            constraint=models.UniqueConstraint(fields=('version', 'snapshot', 'relation', 'location_hash'), name='uniq_evidence_version_snapshot_relation_loc'),
        ),
        migrations.AddIndex(
            model_name='knowledgecandidate',
            index=models.Index(fields=['project', 'state', 'created_at'], name='knowledge_e_project_75c850_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgecandidate',
            index=models.Index(fields=['project', 'kind', 'state'], name='knowledge_e_project_f80df3_idx'),
        ),
    ]
