# Generated by Django 5.2 on 2026-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0002_knowledgeasset_knowledgeversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecandidate',
            name='dedup_key',
            field=models.CharField(help_text='去重键：project + kind + 归一化内容哈希', max_length=255, unique=True),
        ),
    ]
