# Generated by Django 5.2 on 2026-09-29 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0003_alter_knowledgecandidate_dedup_key'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('suite_type', models.CharField(choices=[('seed', '种子集'), ('regression', '回归集'), ('fresh', '新鲜集'), ('challenge', '挑战集')], db_index=True, max_length=20)),
                ('task_type', models.CharField(choices=[('knowledge_query', '知识库问答'), ('code_review', '代码审查'), ('test_execution', '测试执行'), ('testcase_generation', '用例生成')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('split_ratio', models.JSONField(blank=True, default=dict, help_text="split 比例：{'gold': 0.2, 'regression': 0.5, 'fresh': 0.2, 'challenge': 0.1}")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_suites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_suites', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.PositiveIntegerField()),
                ('task_type', models.CharField(choices=[('knowledge_query', '知识库问答'), ('code_review', '代码审查'), ('test_execution', '测试执行'), ('testcase_generation', '用例生成')], max_length=32)),
                ('input_payload', models.JSONField(default=dict, help_text='输入：query/diff/requirement/测试计划')),
                ('expected_payload', models.JSONField(blank=True, default=dict, help_text='期望输出/标准答案/评分要点')),
                ('golden_labels', models.JSONField(blank=True, default=dict, help_text='人工标注：正确/错误/应召回证据/应拒绝项')),
                ('split', models.CharField(choices=[('gold', 'Gold'), ('regression', 'Regression'), ('fresh', 'Fresh'), ('challenge', 'Challenge')], db_index=True, default='regression', max_length=20)),
                ('annotator', models.CharField(blank=True, help_text='标注人/脚本名', max_length=255)),
                ('annotated_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_cases', to='knowledge_evolution.generationoutput')),
                ('source_trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_cases', to='knowledge_evolution.retrievaltrace')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='knowledge_evolution.evaluationsuite')),
            ],
            options={
                'ordering': ['suite', 'case_number'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationsuite',
            index=models.Index(fields=['project', 'suite_type', 'task_type'], name='knowledge_e_project_d982d4_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationsuite',
            index=models.Index(fields=['project', 'is_active'], name='knowledge_e_project_7c531e_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationsuite',
            constraint=models.UniqueConstraint(fields=('project', 'name', 'suite_type'), name='uniq_suite_project_name_type'),
        ),
        migrations.AddIndex(
            model_name='evaluationcase',
            index=models.Index(fields=['suite', 'split'], name='knowledge_e_suite_i_79622d_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationcase',
            index=models.Index(fields=['task_type', 'split'], name='knowledge_e_task_ty_0f1c0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcase',
            constraint=models.UniqueConstraint(fields=('suite', 'case_number'), name='uniq_case_suite_number'),
        ),
    ]
