# Generated by Django 5.2 on 2026-09-29 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0004_evaluationsuite_evaluationcase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexprojection',
            name='state',
            field=models.CharField(choices=[('pending', '待写入'), ('writing', '写入中'), ('ready', '已就绪'), ('failed', '写入失败'), ('stale', '已过期'), ('rolled_back', '已回滚'), ('removed', '已回收')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='IndexProjectionOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vector_id', models.CharField(db_index=True, max_length=128)),
                ('operation', models.CharField(choices=[('upsert', '写入/更新'), ('delete', '删除')], db_index=True, max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='向量、payload、稀疏向量等')),
                ('state', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='knowledge_evolution.indexprojection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['projection', 'state', 'created_at'], name='knowledge_e_project_4c72a4_idx'), models.Index(fields=['projection', 'vector_id', '-created_at'], name='knowledge_e_project_f35819_idx')],
            },
        ),
    ]

