# Generated by Django 5.2 on 2026-09-29 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0020_documentchunk_block_type_documentchunk_location_and_more'),
        ('knowledge_evolution', '0005_alter_indexprojection_state_indexprojectionoutbox'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('document', '文档'), ('section', '章节'), ('chunk', '分块'), ('concept', '概念'), ('rule', '规则/约束'), ('fact', '事实'), ('procedure', '流程/步骤'), ('evidence', '证据'), ('asset', '知识资产'), ('version', '知识版本'), ('candidate', '知识候选'), ('source', '来源快照')], db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, help_text='项目级稳定节点 ID', max_length=255)),
                ('name', models.CharField(blank=True, max_length=500)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge_evolution.knowledgeasset')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge_evolution.knowledgecandidate')),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge.documentchunk')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph_nodes', to='projects.project')),
                ('projection', models.ForeignKey(blank=True, help_text='所属投影；为空表示事实层全局图', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge_evolution.indexprojection')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge_evolution.sourcesnapshot')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='knowledge_evolution.knowledgeversion')),
            ],
            options={
                'ordering': ['project', 'node_type', 'external_id'],
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('CONTAINS', '包含'), ('PART_OF', '属于'), ('NEXT', '下一项'), ('MENTIONS', '提及'), ('DEFINES', '定义'), ('REFINES', '细化'), ('CONTRADICTS', '矛盾'), ('SUPERSEDES', '取代'), ('SUPPORTED_BY', '由…支持'), ('DERIVED_FROM', '派生自'), ('ACCEPTED_BY', '被…采纳'), ('REFUTED_BY', '被…反驳')], db_index=True, max_length=32)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('weight', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_graph_edges', to='projects.project')),
                ('projection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_edges', to='knowledge_evolution.indexprojection')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='knowledge_evolution.graphnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='knowledge_evolution.graphnode')),
            ],
            options={
                'ordering': ['-weight', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['project', 'node_type', 'created_at'], name='knowledge_e_project_869af3_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['project', 'projection', 'node_type'], name='knowledge_e_project_00097c_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['snapshot', 'node_type'], name='knowledge_e_snapsho_0270d0_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['asset', 'node_type'], name='knowledge_e_asset_i_a56f15_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('project', 'external_id'), name='uniq_graphnode_project_external_id'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['project', 'relation', 'created_at'], name='knowledge_e_project_fc82c3_idx'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['from_node', 'relation'], name='knowledge_e_from_no_af8d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['to_node', 'relation'], name='knowledge_e_to_node_5399ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphedge',
            constraint=models.UniqueConstraint(fields=('project', 'projection', 'from_node', 'to_node', 'relation'), name='uniq_graphedge_project_proj_from_to_rel'),
        ),
    ]
