# Generated by Django 5.2 on 2026-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0007_retrievalpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackevent',
            name='detail',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
