# Generated by Django 5.2 on 2026-09-29 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0008_feedbackevent_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='运行配置：executor_id / policy_id / model_version / top_k 等')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20)),
                ('metrics_summary', models.JSONField(blank=True, default=dict)),
                ('cost_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='knowledge_evolution.evaluationsuite')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('skipped', '已跳过')], db_index=True, default='pending', max_length=20)),
                ('predicted_payload', models.JSONField(blank=True, default=dict)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('token_usage', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
                ('l0_score', models.FloatField(blank=True, null=True)),
                ('l1_score', models.FloatField(blank=True, null=True)),
                ('l2_score', models.FloatField(blank=True, null=True)),
                ('l3_score', models.FloatField(blank=True, null=True)),
                ('raw_scores', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='knowledge_evolution.evaluationcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='knowledge_evolution.evaluationrun')),
            ],
            options={
                'ordering': ['run', 'case__case_number'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['suite', 'status', 'created_at'], name='knowledge_e_suite_i_668a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['run', 'status'], name='knowledge_e_run_id_64c545_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationresult',
            index=models.Index(fields=['case', 'status'], name='knowledge_e_case_id_8e8084_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationresult',
            constraint=models.UniqueConstraint(fields=('run', 'case'), name='uniq_evalresult_run_case'),
        ),
    ]
