# Generated by Django 5.x on 2026-09-30 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_evolution", "0010_capability_release_and_workflow_graph"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generationoutput",
            name="trace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generation_outputs",
                to="knowledge_evolution.retrievaltrace",
            ),
        ),
    ]
