# Generated by Django 5.x on 2026-09-30 13:30

from django.db import migrations, models


def _migrate_json_version_ids_to_m2m(apps, schema_editor):
    FeedbackEvent = apps.get_model("knowledge_evolution", "FeedbackEvent")
    KnowledgeVersion = apps.get_model("knowledge_evolution", "KnowledgeVersion")
    for event in FeedbackEvent.objects.iterator():
        raw_ids = event.knowledge_version_ids or []
        version_ids = [v for v in raw_ids if v]
        if version_ids:
            versions = list(KnowledgeVersion.objects.filter(id__in=version_ids))
            event.knowledge_versions.set(versions)


def _revert_m2m_to_json(apps, schema_editor):
    FeedbackEvent = apps.get_model("knowledge_evolution", "FeedbackEvent")
    for event in FeedbackEvent.objects.iterator():
        ids = list(event.knowledge_versions.values_list("id", flat=True))
        event.knowledge_version_ids = ids
        event.save(update_fields=["knowledge_version_ids"])


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_evolution", "0011_alter_generationoutput_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackevent",
            name="knowledge_versions",
            field=models.ManyToManyField(
                blank=True,
                related_name="feedback_events",
                to="knowledge_evolution.knowledgeversion",
            ),
        ),
        migrations.RunPython(
            _migrate_json_version_ids_to_m2m,
            _revert_m2m_to_json,
        ),
        migrations.RemoveField(
            model_name="feedbackevent",
            name="knowledge_version_ids",
        ),
    ]
