# Generated by Django 5.2 on 2026-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0013_capabilitydefinition_generationoutput_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphnode',
            name='node_type',
            field=models.CharField(choices=[('document', '文档'), ('section', '章节'), ('chunk', '分块'), ('concept', '概念'), ('rule', '规则/约束'), ('fact', '事实'), ('procedure', '流程/步骤'), ('evidence', '证据'), ('asset', '知识资产'), ('version', '知识版本'), ('candidate', '知识候选'), ('source', '来源快照'), ('workflow_output', '流程产出'), ('requirement_document', '需求文档'), ('requirement_module', '需求模块'), ('test_case', '测试用例'), ('test_step', '测试步骤'), ('test_module', '测试模块')], db_index=True, max_length=32),
        ),
    ]
