# Generated by Django 5.2.6 on 2026-09-30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_evolution", "0019_alter_evaluationcase_split_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("window_key", models.CharField(max_length=128)),
                ("metrics", models.JSONField(default=dict)),
                ("thresholds", models.JSONField(default=dict)),
                ("breaches", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("healthy", "健康"), ("breached", "超阈值")], db_index=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="capability_release_observations", to=settings.AUTH_USER_MODEL)),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="observations", to="knowledge_evolution.capabilityrelease")),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["release", "status", "created_at"], name="knowledge_e_release_792a09_idx")],
                "constraints": [models.UniqueConstraint(fields=("release", "window_key"), name="uniq_release_observation_window")],
            },
        ),
    ]
