# Generated by Django 5.2 on 2026-10-01 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0022_skill_workflow_stages'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capabilityrelease',
            name='uniq_capability_release_version',
        ),
        migrations.AlterField(
            model_name='capabilitydefinition',
            name='kind',
            field=models.CharField(choices=[('knowledge', '知识'), ('retrieval_policy', '检索策略'), ('prompt', 'Prompt'), ('skill', 'Skill'), ('agent', 'Agent'), ('composite', '复合能力')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='capabilityrelease',
            name='kind',
            field=models.CharField(choices=[('knowledge', '知识'), ('retrieval_policy', '检索策略'), ('prompt', 'Prompt'), ('skill', 'Skill'), ('agent', 'Agent'), ('composite', '复合能力')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='capabilityrelease',
            name='state',
            field=models.CharField(choices=[('draft', '草稿'), ('validating', '校验中'), ('shadow', '影子验证'), ('awaiting_approval', '待审批'), ('active', '生产生效'), ('retired', '已退役'), ('rolled_back', '已回滚'), ('rejected', '未通过'), ('quarantined', '已隔离')], db_index=True, default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='promotiondecision',
            name='decision',
            field=models.CharField(choices=[('approved', '通过'), ('rejected', '驳回'), ('rollback', '回滚'), ('quarantine', '隔离')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='capabilityrelease',
            constraint=models.UniqueConstraint(fields=('project', 'kind', 'name', 'version'), name='uniq_capability_release_version'),
        ),
        migrations.AddConstraint(
            model_name='capabilityrelease',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('project', 'kind', 'name'), name='uniq_active_release_per_target'),
        ),
    ]
