# Generated by Django 5.2 on 2026-10-01 08:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0023_remove_capabilityrelease_uniq_capability_release_version_and_more'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('skills', '0004_migrate_existing_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generationoutput',
            name='skill_package_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='generationoutput',
            name='skill_version',
            field=models.ForeignKey(blank=True, help_text='产出生成时锁定的 Skill 版本，用于归因与复现', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_outputs', to='skills.skillversion', verbose_name='Skill 版本'),
        ),
        migrations.AlterField(
            model_name='knowledgeauditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('transition', '状态流转'), ('publish', '发布'), ('rollback', '回滚'), ('conflict_resolved', '冲突裁决'), ('acl_change', '权限变更'), ('validate', '包校验'), ('download', '下载导出'), ('quarantine', '隔离')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='WorkflowSkillLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=128)),
                ('lock_key', models.CharField(db_index=True, help_text='锁的定位键：四阶段用阶段名，单能力用能力标识或 default', max_length=128)),
                ('scope', models.CharField(choices=[('single', '单能力'), ('workflow', '四阶段流水线'), ('composite', '复合能力')], default='single', max_length=16)),
                ('stage', models.CharField(blank=True, db_index=True, max_length=32)),
                ('package_sha256', models.CharField(blank=True, help_text='锁定时刻的包哈希，用于事后核对锁指向的确实是同一份内容', max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('locked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_skill_locks', to='knowledge_evolution.capabilitydefinition')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_skill_locks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_skill_locks', to='projects.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_skill_locks', to='knowledge_evolution.capabilityrelease')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_locks', to='skills.skill')),
                ('skill_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_locks', to='skills.skillversion')),
            ],
            options={
                'ordering': ['workflow_id', 'locked_at'],
                'indexes': [models.Index(fields=['project', 'workflow_id'], name='ke_skill_lock_proj_wf_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'workflow_id', 'lock_key'), name='uniq_workflow_skill_lock')],
            },
        ),
    ]
