# Generated by Django 5.2 on 2026-10-01 09:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0024_generationoutput_skill_package_sha256_and_more'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('skills', '0004_migrate_existing_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackevent',
            name='capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='knowledge_evolution.capabilitydefinition'),
        ),
        migrations.AddField(
            model_name='feedbackevent',
            name='capability_kind',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='feedbackevent',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='feedbackevent',
            name='release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='knowledge_evolution.capabilityrelease'),
        ),
        migrations.AddField(
            model_name='feedbackevent',
            name='skill_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_events', to='skills.skillversion'),
        ),
        migrations.CreateModel(
            name='EvaluationGateSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('partition', '分区完整性'), ('baseline', '基线可比性'), ('hard_gate', '硬门禁'), ('full', '完整门禁')], db_index=True, default='full', max_length=32)),
                ('partitions', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('baseline_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_gate_snapshots', to='knowledge_evolution.evaluationrun')),
                ('candidate_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_gate_snapshots', to='knowledge_evolution.evaluationrun')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gate_snapshots', to=settings.AUTH_USER_MODEL)),
                ('gold_dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_snapshots', to='knowledge_evolution.golddatasetversion')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_gate_snapshots', to='projects.project')),
                ('release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_snapshots', to='knowledge_evolution.capabilityrelease')),
                ('skill_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_snapshots', to='skills.skillversion')),
                ('suite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_snapshots', to='knowledge_evolution.evaluationsuite')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'passed', 'created_at'], name='ke_gate_proj_pass_idx')],
                'constraints': [models.UniqueConstraint(fields=('candidate_run', 'kind', 'content_hash'), name='uniq_gate_snapshot_run_kind_hash')],
            },
        ),
    ]
