# Generated by Django 5.2 on 2026-10-01 09:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0025_feedbackevent_capability_and_more'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capabilityrelease',
            name='approval_snapshot_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='capabilityrelease',
            name='observation_state',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='failureattribution',
            name='layer',
            field=models.CharField(choices=[('intent', '意图层'), ('planning', '规划层'), ('prompt', 'Prompt层'), ('knowledge', '知识层'), ('retrieval', '检索层'), ('skill_tool', 'Skill/工具层'), ('environment', '执行环境层'), ('downstream', '下游结果层')], db_index=True, default='skill_tool', max_length=24),
        ),
        migrations.AlterField(
            model_name='failureattribution',
            name='category',
            field=models.CharField(choices=[('intent_error', '理解失败'), ('planning_error', '规划失败'), ('knowledge_missing', '知识缺失'), ('knowledge_stale', '知识过期'), ('retrieval_error', '检索失败'), ('prompt_error', 'Prompt失败'), ('tool_error', '工具失败'), ('generation_error', '生成失败'), ('environment_error', '执行环境失败'), ('downstream_execution_error', '下游执行失败')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='knowledgeauditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('transition', '状态流转'), ('publish', '发布'), ('rollback', '回滚'), ('conflict_resolved', '冲突裁决'), ('acl_change', '权限变更'), ('validate', '包校验'), ('download', '下载导出'), ('quarantine', '隔离'), ('submit_approval', '提交审批'), ('approve', '审批通过'), ('reject', '驳回')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='failureattribution',
            index=models.Index(fields=['project', 'layer', 'state'], name='knowledge_e_project_47d18c_idx'),
        ),
    ]
