# Generated by Django 5.2 on 2026-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0026_capabilityrelease_approval_snapshot_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failureattribution',
            name='layer',
            field=models.CharField(blank=True, choices=[('intent', '意图层'), ('planning', '规划层'), ('prompt', 'Prompt层'), ('knowledge', '知识层'), ('retrieval', '检索层'), ('skill_tool', 'Skill/工具层'), ('environment', '执行环境层'), ('downstream', '下游结果层')], db_index=True, default='', max_length=24),
        ),
    ]
