# Generated by Django 5.2 on 2026-10-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0027_alter_failureattribution_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstagegate',
            name='detail',
            field=models.JSONField(
                blank=True, default=dict,
                help_text=(
                    '门禁的可核验明细：报告契约校验结果（report_contract）与'
                    '阶段/端到端评测结论（evaluation）。状态机只由 status 决定，'
                    '这里只存证据，不参与流转判定。'
                ),
            ),
        ),
    ]
