# Generated by Django 5.2 on 2026-10-04 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0033_testassettaxonomy_gold_scope_and_candidates'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCandidateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('stage_output', '正式阶段产出'), ('feedback', '人工反馈'), ('history_import', '历史资料导入')], db_index=True, max_length=24)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('signal', models.CharField(blank=True, db_index=True, max_length=32)),
                ('idempotency_key', models.CharField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('needs_review', '待人工审核'), ('completed', '已处理'), ('failed', '处理失败'), ('dead_letter', '死信')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('preflight', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_events', to='knowledge_evolution.goldcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_candidate_events', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status', 'created_at'], name='knowledge_e_project_79579e_idx'), models.Index(fields=['project', 'source_type', 'created_at'], name='knowledge_e_project_54feaa_idx')],
            },
        ),
    ]
