# Generated by Django 5.2 on 2026-10-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0034_assetcandidateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldannotation',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='goldannotation',
            name='review_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='goldannotation',
            name='split',
            field=models.CharField(blank=True, choices=[('gold', 'Gold'), ('regression', 'Regression'), ('fresh', 'Fresh'), ('challenge', 'Challenge'), ('hidden', 'Hidden')], max_length=20),
        ),
        migrations.AddField(
            model_name='goldannotation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='golddatasetversion',
            name='governance_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='knowledgeauditlog',
            name='action',
            field=models.CharField(choices=[('create', '创建'), ('transition', '状态流转'), ('publish', '发布'), ('rollback', '回滚'), ('conflict_resolved', '冲突裁决'), ('acl_change', '权限变更'), ('validate', '包校验'), ('download', '下载导出'), ('quarantine', '隔离'), ('submit_approval', '提交审批'), ('approve', '审批通过'), ('reject', '驳回'), ('annotate', '人工审核'), ('freeze', '冻结版本')], db_index=True, max_length=32),
        ),
    ]
