# Generated by Django 5.2 on 2026-10-04 08:28
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_management", "0004_alter_filereference_ref_type"),
        ("knowledge_evolution", "0035_gold_annotation_governance_and_freeze"),
        ("projects", "0004_remove_project_password_remove_project_system_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(name="HistoryImportBatch", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("name", models.CharField(max_length=255)),
            ("status", models.CharField(choices=[("preflight", "已预检"), ("confirmed", "已确认"), ("completed", "已导入"), ("failed", "失败")], db_index=True, default="preflight", max_length=16)),
            ("manifest", models.JSONField(default=dict)),
            ("manifest_hash", models.CharField(db_index=True, max_length=64)),
            ("preflight", models.JSONField(default=dict)),
            ("candidate_count", models.PositiveIntegerField(default=0)),
            ("confirmed_at", models.DateTimeField(blank=True, null=True)),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("confirmed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="confirmed_history_import_batches", to=settings.AUTH_USER_MODEL)),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_history_import_batches", to=settings.AUTH_USER_MODEL)),
            ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history_import_batches", to="projects.project")),
        ], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="HistoryImportItem", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("role", models.CharField(choices=[("requirement", "需求"), ("plan", "真实方案"), ("case", "真实用例"), ("execution", "执行结果"), ("report", "测试报告")], max_length=16)),
            ("file_hash", models.CharField(max_length=64)),
            ("metadata", models.JSONField(blank=True, default=dict)),
            ("batch", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="knowledge_evolution.historyimportbatch")),
            ("file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="file_management.fileasset")),
        ]),
        migrations.CreateModel(name="HistoryReplay", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("status", models.CharField(choices=[("draft", "草稿"), ("running", "回放中"), ("needs_review", "待判定"), ("passed", "通过"), ("blocked", "已阻断"), ("failed", "失败")], db_index=True, default="draft", max_length=20)),
            ("execution_lock", models.JSONField(default=dict)),
            ("config_hash", models.CharField(db_index=True, max_length=64)),
            ("stage_scores", models.JSONField(blank=True, default=dict)),
            ("summary", models.JSONField(blank=True, default=dict)),
            ("gate_report", models.JSONField(blank=True, default=dict)),
            ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="replays", to="knowledge_evolution.historyimportbatch")),
            ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_history_replays", to=settings.AUTH_USER_MODEL)),
            ("flywheel_run", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="history_replay", to="knowledge_evolution.flywheelrun")),
            ("gold_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="history_replays", to="knowledge_evolution.golddatasetversion")),
            ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history_replays", to="projects.project")),
        ]),
        migrations.CreateModel(name="HistoryReplayDifference", fields=[
            ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ("stage", models.CharField(db_index=True, max_length=32)),
            ("case_key", models.CharField(db_index=True, max_length=255)),
            ("category", models.CharField(choices=[("missing", "缺失"), ("extra", "新增"), ("conflict", "冲突"), ("equivalent", "等价"), ("uncertain", "不确定")], db_index=True, max_length=16)),
            ("expected", models.JSONField(blank=True, default=dict)),
            ("actual", models.JSONField(blank=True, default=dict)),
            ("evidence", models.JSONField(blank=True, default=list)),
            ("critical", models.BooleanField(db_index=True, default=False)),
            ("human_decision", models.CharField(blank=True, choices=[("equivalent", "等价"), ("regression", "退化"), ("acceptable", "可接受")], max_length=16)),
            ("decision_note", models.TextField(blank=True)),
            ("decided_at", models.DateTimeField(blank=True, null=True)),
            ("decided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="decided_history_differences", to=settings.AUTH_USER_MODEL)),
            ("replay", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="differences", to="knowledge_evolution.historyreplay")),
        ], options={"ordering": ["stage", "case_key"]}),
        migrations.CreateModel(name="ProjectFlywheelSetting", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("enabled", models.BooleanField(db_index=True, default=False)),
            ("rollout_note", models.TextField(blank=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="flywheel_setting", to="projects.project")),
            ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_flywheel_settings", to=settings.AUTH_USER_MODEL)),
        ]),
        migrations.AddConstraint(model_name="historyimportbatch", constraint=models.UniqueConstraint(fields=("project", "manifest_hash"), name="uniq_history_manifest_project")),
        migrations.AddConstraint(model_name="historyimportitem", constraint=models.UniqueConstraint(fields=("batch", "role", "file"), name="uniq_history_batch_role_file")),
    ]
