# Generated by Django 5.2 on 2026-10-05 04:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0036_historyimportbatch_historyimportitem_historyreplay_and_more'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('skills', '0005_skill_declared_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageExecutionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=128)),
                ('stage', models.CharField(choices=[('test_plan_generation', '测试方案生成'), ('testcase_generation', '测试用例生成'), ('test_execution', '测试执行'), ('report_generation', '报告生成'), ('risk_identification', '风险识别'), ('issue_tracking', '问题跟踪')], db_index=True, max_length=32)),
                ('skill_package_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('parent_output_ids', models.JSONField(blank=True, default=list)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('entry_type', models.CharField(choices=[('requirement', '需求管理'), ('chat', 'Agent 对话'), ('test_management', '测试管理'), ('flywheel', '质量飞轮'), ('history_replay', '历史回放')], default='flywheel', max_length=24)),
                ('status', models.CharField(choices=[('planned', '已计划'), ('dispatched', '已派发'), ('running', '运行中'), ('output_published', '已发布产出'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消'), ('timed_out', '已超时')], db_index=True, default='planned', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_summary', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict, help_text='执行参数的快照与扩展明细；状态机只由 status 决定，这里不参与判定。')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('output_published_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flywheel_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_attempts', to='knowledge_evolution.flywheelrun')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_attempts', to='knowledge_evolution.generationoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_attempts', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_attempts', to=settings.AUTH_USER_MODEL)),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='knowledge_evolution.stageexecutionattempt')),
                ('skill_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_attempts', to='skills.skillversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'workflow_id', 'stage'], name='ke_attempt_proj_wf_stage_idx'), models.Index(fields=['project', 'status', 'created_at'], name='ke_attempt_proj_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('project', 'idempotency_key'), name='uniq_stage_attempt_idempotency')],
            },
        ),
    ]
