# Generated by Django 5.2 on 2026-10-05 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0037_stageexecutionattempt'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('skills', '0005_skill_declared_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageExecutionContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=128)),
                ('stage', models.CharField(choices=[('test_plan_generation', '测试方案生成'), ('testcase_generation', '测试用例生成'), ('test_execution', '测试执行'), ('report_generation', '报告生成'), ('risk_identification', '风险识别'), ('issue_tracking', '问题跟踪')], db_index=True, max_length=32)),
                ('entry_type', models.CharField(choices=[('requirement', '需求管理'), ('chat', 'Agent 对话'), ('test_management', '测试管理'), ('flywheel', '质量飞轮'), ('history_replay', '历史回放')], default='flywheel', max_length=24)),
                ('channel', models.CharField(blank=True, max_length=16)),
                ('module_key', models.CharField(blank=True, max_length=64)),
                ('skill_package_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('parent_output_ids', models.JSONField(blank=True, default=list)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolve_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_contexts', to='knowledge_evolution.stageexecutionattempt')),
                ('flywheel_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_contexts', to='knowledge_evolution.flywheelrun')),
                ('issued_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_execution_contexts', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_execution_contexts', to='projects.project')),
                ('skill_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_contexts', to='skills.skillversion')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'workflow_id', 'stage'], name='ke_ctx_proj_wf_stage_idx'), models.Index(fields=['expires_at'], name='ke_ctx_expires_idx')],
            },
        ),
    ]
