# Generated by Django 5.2 on 2026-10-05 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0038_stageexecutioncontext'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageDerivedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('stage', models.CharField(choices=[('test_plan_generation', '测试方案生成'), ('testcase_generation', '测试用例生成'), ('test_execution', '测试执行'), ('report_generation', '报告生成'), ('risk_identification', '风险识别'), ('issue_tracking', '问题跟踪')], db_index=True, max_length=32)),
                ('kind', models.CharField(choices=[('evidence_graph', '执行证据图谱'), ('quality_summary', '阶段质量摘要'), ('review_report', '阶段确认报告')], db_index=True, max_length=32)),
                ('filename', models.CharField(max_length=200)),
                ('path', models.CharField(help_text='相对 MEDIA_ROOT 的路径', max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('generator_version', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_output_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('level', models.CharField(blank=True, max_length=8)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_artifacts', to='knowledge_evolution.stageexecutionattempt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_derived_artifacts', to=settings.AUTH_USER_MODEL)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_artifacts', to='knowledge_evolution.generationoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_derived_artifacts', to='projects.project')),
            ],
            options={
                'ordering': ['output', 'kind'],
                'indexes': [models.Index(fields=['project', 'stage', 'kind'], name='ke_derived_proj_stage_kind_idx'), models.Index(fields=['workflow_id', 'kind'], name='ke_derived_wf_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('output', 'kind'), name='uniq_stage_derived_artifact_output_kind')],
            },
        ),
    ]
