# Generated by Django 5.2 on 2026-10-05 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_filereference_ref_type'),
        ('knowledge_evolution', '0039_stagederivedartifact'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageFeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(db_index=True, max_length=32)),
                ('workflow_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('stage', models.CharField(db_index=True, max_length=64)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('retired_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retire_reason', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_attachments', to='knowledge_evolution.stageexecutionattempt')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_feedback_attachments', to='file_management.fileasset')),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_attachments', to='knowledge_evolution.generationoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_feedback_attachments', to='projects.project')),
                ('retired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_stage_attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_stage_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project', 'stage', 'purpose'], name='ke_attach_proj_stage_idx'), models.Index(fields=['output', 'purpose'], name='ke_attach_output_purpose_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'workflow_id', 'stage', 'purpose', 'sha256'), name='uniq_stage_feedback_attachment_file')],
            },
        ),
    ]
