# Generated by Django 5.2 on 2026-10-05 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0040_stagefeedbackattachment'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        ('skills', '0005_skill_declared_stage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStageSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=128)),
                ('stage', models.CharField(choices=[('test_plan_generation', '测试方案生成'), ('testcase_generation', '测试用例生成'), ('test_execution', '测试执行'), ('report_generation', '报告生成'), ('risk_identification', '风险识别'), ('issue_tracking', '问题跟踪')], db_index=True, max_length=32)),
                ('target', models.CharField(choices=[('new_workflow', '纳入新流程'), ('existing_workflow', '纳入已有流程')], default='existing_workflow', max_length=24)),
                ('package_sha256', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(choices=[('admitted', '已纳管'), ('superseded', '已被替换')], db_index=True, default='admitted', max_length=16)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stage_submissions', to=settings.AUTH_USER_MODEL)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_submissions', to='knowledge_evolution.generationoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_stage_submissions', to='projects.project')),
                ('skill_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_stage_submissions', to='skills.skillversion')),
                ('supersedes_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by_submissions', to='knowledge_evolution.generationoutput')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow_id', 'stage'], name='ke_submit_wf_stage_idx'), models.Index(fields=['project', 'stage', 'state'], name='ke_submit_proj_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'output', 'stage'), name='uniq_stage_submission_output_stage')],
            },
        ),
    ]
