# Generated by Django 5.2 on 2026-10-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0041_workflowstagesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationproposal',
            name='proposal_type',
            field=models.CharField(choices=[('prompt', 'Prompt'), ('knowledge', '知识'), ('retrieval_policy', '检索策略'), ('skill_tool', 'Skill/工具配置'), ('skill_content', 'Skill 内容')], db_index=True, max_length=32),
        ),
    ]
