# Generated by Django 5.2 on 2026-10-06 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0042_alter_optimizationproposal_proposal_type'),
        ('projects', '0004_remove_project_password_remove_project_system_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlywheelRegistrationFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_id', models.CharField(db_index=True, max_length=128)),
                ('stage', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', '待补偿'), ('failed', '补偿失败'), ('dead_letter', '死信'), ('resolved', '已解决')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('last_error', models.TextField(blank=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output', models.ForeignKey(help_text='业务侧已经落库的正式产出：它的存在与可访问性不因登记失败而改变', on_delete=django.db.models.deletion.CASCADE, related_name='registration_failures', to='knowledge_evolution.generationoutput')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flywheel_registration_failures', to='projects.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_registration_failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='ke_regfail_proj_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('output', 'workflow_id', 'stage'), name='uniq_registration_failure_output_stage')],
            },
        ),
    ]
