# Generated by Django 5.2 on 2026-08-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0007_alter_apiinterface_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinterface',
            name='status',
            field=models.CharField(blank=True, choices=[('self_testing', '自测中'), ('integrating', '联调中'), ('completed', '已完成'), ('deprecated', '已废弃')], default='self_testing', max_length=20, verbose_name='Status'),
        ),
    ]
