# Generated by Django 5.2 on 2026-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_interfaces', '0009_remove_apiinterface_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinterface',
            name='path_params',
            field=models.JSONField(blank=True, default=list, verbose_name='Path Params'),
        ),
    ]
