# Generated by Codex
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api_interfaces', '0008_alter_apiinterface_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apiinterface',
            unique_together=set(),
        ),
    ]