# Generated by Django 5.2 on 2026-08-27 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0021_remove_uienvironmentconfig_browser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiAuthState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('state_json', models.JSONField(blank=True, null=True, verbose_name='登录态快照')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ui_auth_states', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('env_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_states', to='ui_automation.uienvironmentconfig', verbose_name='所属环境')),
            ],
            options={
                'verbose_name': '环境登录态',
                'verbose_name_plural': '环境登录态',
                'db_table': 'ui_auth_state',
                'ordering': ['-updated_at'],
            },
        ),
    ]
