# Generated by Django 5.2 on 2026-09-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0022_uiauthstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='uipagesteps',
            name='auth_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_steps', to='ui_automation.uiauthstate', verbose_name='绑定登录态'),
        ),
    ]
