# Generated by Django 5.2 on 2026-09-15 13:05

import base64
import hashlib

from cryptography.fernet import Fernet
from django.conf import settings
from django.db import migrations, models


def copy_active_platform_llm(apps, schema_editor):
    """首次升级时复制当前通用配置，升级后两套配置彼此独立。"""
    LLMConfig = apps.get_model('langgraph_integration', 'LLMConfig')
    CodeAnalysisLLMConfig = apps.get_model('code_analysis', 'CodeAnalysisLLMConfig')
    source = LLMConfig.objects.filter(is_active=True).order_by('pk').first()
    if not source:
        return
    digest = hashlib.sha256(settings.SECRET_KEY.encode('utf-8')).digest()
    cipher = Fernet(base64.urlsafe_b64encode(digest))
    encrypted_key = cipher.encrypt(source.api_key.encode('utf-8')).decode('ascii') if source.api_key else ''
    CodeAnalysisLLMConfig.objects.create(
        config_name=f'代码审查专用 - {source.config_name}', name=source.name,
        api_url=source.api_url, encrypted_api_key=encrypted_key,
        request_timeout=max(30, source.request_timeout or 600),
        max_retries=source.max_retries, is_active=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('code_analysis', '0011_analysis_queue_and_degraded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAnalysisLLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(default='代码审查 LLM', max_length=255, verbose_name='配置名称')),
                ('name', models.CharField(max_length=255, verbose_name='模型名称')),
                ('api_url', models.URLField(max_length=2048, verbose_name='API 地址')),
                ('encrypted_api_key', models.TextField(blank=True, default='', verbose_name='加密 API Key')),
                ('request_timeout', models.PositiveIntegerField(default=600, verbose_name='请求超时秒数')),
                ('max_retries', models.PositiveSmallIntegerField(default=2, verbose_name='最大重试次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '代码审查 LLM 配置',
                'verbose_name_plural': '代码审查 LLM 配置',
            },
        ),
        migrations.RunPython(copy_active_platform_llm, migrations.RunPython.noop),
    ]
