# Generated by Django 5.2 on 2026-10-01 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_evolution', '0023_remove_capabilityrelease_uniq_capability_release_version_and_more'),
        ('skills', '0002_alter_skill_description_alter_skill_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='capability',
            field=models.ForeignKey(blank=True, help_text='一个 Skill 绑定一个可进化能力定义，用于评测与发布治理', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='knowledge_evolution.capabilitydefinition', verbose_name='绑定能力'),
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(help_text='SemVer 或可比较的版本字符串，如 1.2.0、0.0.0-migrated', max_length=100, verbose_name='版本号')),
                ('package_path', models.CharField(help_text='相对 MEDIA_ROOT 的不可变存储目录', max_length=500, verbose_name='包存储路径')),
                ('package_sha256', models.CharField(db_index=True, help_text='基于标准化文件清单与内容的 SHA-256（见 skills.packaging）', max_length=64, verbose_name='包哈希')),
                ('manifest', models.JSONField(blank=True, default=dict, help_text='版本、阶段、入口、输入/输出 Schema、依赖与权限声明', verbose_name='版本清单')),
                ('validation_report', models.JSONField(blank=True, default=dict, help_text='结构、密钥、静态扫描与 Schema 校验结果', verbose_name='校验报告')),
                ('source_type', models.CharField(choices=[('upload', '本地上传'), ('git', 'Git 导入'), ('store', 'Skill 商店'), ('evolution', '自进化派生'), ('migration', '存量迁移')], db_index=True, default='upload', max_length=16, verbose_name='来源类型')),
                ('source_metadata', models.JSONField(blank=True, default=dict, help_text='原始文件名、Git URL/commit、商店条目、上传人等', verbose_name='来源元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('previous_version', models.ForeignKey(blank=True, help_text='用于 diff 与回滚的派生来源', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='skills.skillversion', verbose_name='父版本')),
                ('release', models.OneToOneField(blank=True, help_text='kind=skill 的发布单元，承载本版本的发布状态与门禁快照', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_version', to='knowledge_evolution.capabilityrelease', verbose_name='发布单元')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='skills.skill', verbose_name='所属 Skill')),
            ],
            options={
                'verbose_name': 'Skill 版本',
                'verbose_name_plural': 'Skill 版本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='运行时快速解析用的活跃版本指针；权威状态仍以版本关联的发布单元为准', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_skills', to='skills.skillversion', verbose_name='当前活跃版本'),
        ),
        migrations.AddIndex(
            model_name='skillversion',
            index=models.Index(fields=['skill', '-created_at'], name='skills_skil_skill_i_c27a75_idx'),
        ),
        migrations.AddIndex(
            model_name='skillversion',
            index=models.Index(fields=['source_type', 'created_at'], name='skills_skil_source__3828a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillversion',
            constraint=models.UniqueConstraint(fields=('skill', 'version'), name='uniq_skill_version'),
        ),
        migrations.AddConstraint(
            model_name='skillversion',
            constraint=models.UniqueConstraint(fields=('skill', 'package_sha256'), name='uniq_skill_version_package'),
        ),
    ]
