# Generated by Django 5.2 on 2026-10-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_migrate_existing_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='declared_stage',
            field=models.CharField(blank=True, db_index=True, default='', help_text='manifest 未声明阶段的 Skill 由管理员补填，取值见 capability_registry.STAGE_LABELS', max_length=64, verbose_name='声明能力阶段'),
        ),
    ]
