# Generated by Django 5.2 on 2026-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skillworkshopexclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='上传/导入时由平台生成、人工确认的展示名称；为空时展示 name。不参与逻辑身份与归并', max_length=128, verbose_name='展示名称'),
        ),
    ]
