# Generated by Django 5.2 on 2026-07-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_logs', '0004_anonymized_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymizeddocument',
            name='custom_keywords',
            field=models.JSONField(blank=True, default=list, help_text="如 [{'keyword': '张三', 'replacement': '某某'}, {'keyword': '北京科技有限公司', 'replacement': '某公司'}]", verbose_name='自定义关键词列表'),
        ),
    ]
