# Generated by Django 5.2 on 2026-07-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_logs', '0005_alter_anonymizeddocument_custom_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymizationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板说明')),
                ('enabled_preset_types', models.JSONField(blank=True, default=list, help_text="如 ['PHONE_NUMBER', 'EMAIL_ADDRESS']", verbose_name='预设敏感信息类型')),
                ('custom_keywords', models.JSONField(blank=True, default=list, help_text="如 [{'keyword': '张三', 'replacement': '某某'}]", verbose_name='自定义关键词列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymization_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '脱敏模板',
                'verbose_name_plural': '脱敏模板',
                'ordering': ['-updated_at'],
            },
        ),
    ]
