[supervisord]
nodaemon=true
logfile=/app/data/logs/supervisord.log
pidfile=/app/data/run/supervisord.pid

[program:django]
command=uvicorn wharttest_django.asgi:application --host 0.0.0.0 --port 8000 --workers=1
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/data/logs/django_err.log
stdout_logfile=/app/data/logs/django_out.log

[program:celery_worker]
command=celery -A wharttest_django worker -l info --concurrency=8 -Q celery,task_center
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/data/logs/worker_err.log
stdout_logfile=/app/data/logs/worker_out.log

[program:celery_beat]
command=celery -A wharttest_django beat -l info --schedule=/app/data/celerybeat-schedule
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/data/logs/beat_err.log
stdout_logfile=/app/data/logs/beat_out.log
