# Generated by Django 5.2 on 2026-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_alter_filereference_ref_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filereference',
            name='ref_type',
            field=models.CharField(choices=[('api_interface', '接口'), ('api_testcase', '测试用例'), ('api_interface_case', '接口用例'), ('ui_testcase', 'UI用例'), ('ui_page_steps', 'UI页面步骤'), ('llm_chat', 'LLM对话'), ('knowledge_evolution_feedback', '飞轮阶段补充文件')], max_length=50),
        ),
    ]
